-- MySQL Script generated by MySQL Workbench
-- Wed Oct  4 21:20:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DIM_FILME`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DIM_FILME` (
  `id` INT NOT NULL,
  `nome` VARCHAR(120) NOT NULL,
  `ator_principal` VARCHAR(120),
  `qt_duracao` INT NULL,
  `ds_genero` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIM_VENDEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DIM_VENDEDOR` (
  `id` INT NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIM_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DIM_CLIENTE` (
  `id` INT NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FATO_LOCACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FATO_LOCACAO` (
  `id` INT NOT NULL,
  `vl_locacao` DECIMAL(5,2) NOT NULL,
  `dt_locacao` DATE NOT NULL,
  `DIM_FILME_id` INT NOT NULL,
  `DIM_VENDEDOR_id` INT NOT NULL,
  `DIM_CLIENTE_id` INT NOT NULL,
  PRIMARY KEY (`id`, `DIM_FILME_id`, `DIM_VENDEDOR_id`, `DIM_CLIENTE_id`),
  INDEX `fk_FATO_LOCACAO_DIM_FILME_idx` (`DIM_FILME_id` ASC) VISIBLE,
  INDEX `fk_FATO_LOCACAO_DIM_VENDEDOR1_idx` (`DIM_VENDEDOR_id` ASC) VISIBLE,
  INDEX `fk_FATO_LOCACAO_DIM_CLIENTE1_idx` (`DIM_CLIENTE_id` ASC) VISIBLE,
  CONSTRAINT `fk_FATO_LOCACAO_DIM_FILME`
    FOREIGN KEY (`DIM_FILME_id`)
    REFERENCES `mydb`.`DIM_FILME` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FATO_LOCACAO_DIM_VENDEDOR1`
    FOREIGN KEY (`DIM_VENDEDOR_id`)
    REFERENCES `mydb`.`DIM_VENDEDOR` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FATO_LOCACAO_DIM_CLIENTE1`
    FOREIGN KEY (`DIM_CLIENTE_id`)
    REFERENCES `mydb`.`DIM_CLIENTE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
